SECRETMANAGER_CONFIG: aws-secretsmanager:/production/wee-api
BASE_URL: https://wee.bnking.in/
GRADLE_HOME: /usr/local/gradle
M2: /usr/local/apache-maven/bin
M2_HOME: /usr/local/apache-maven
#SERVER_PORT: "5007"
_JAVA_OPTIONS: -javaagent:/var/newrelic.jar -Dnewrelic.config.app_name=wee-api-eks -Dnewrelic.config.license_key=7e496d7961ed578c800942b3fd949672fd3dNRAL -Xms256m
